# docker-compose.yml
version: '2'
services:
    db:
      image: centos/mysql-57-centos7
      ports:
        - 3306:3306
      volumes:
        - ./data/db:/var/lib/mysql-files
      environment:
        MYSQL_ROOT_PASSWORD: root

    nginx:
      build: ./nginx
#      image: centos/nginx-18-centos7
      links:
        - php
      volumes:
        - ./nginx/nginx.conf:/etc/nginx/nginx.conf
        - ./www:/var/www
        - ./log:/var/log/nginx
      ports:
        - 8088:80

    redis:
        image: centos/redis-32-centos7
        ports:
            - 6379:6379

    php:
        image: php-test-app
        links:
            - db:mysqldb
            - redis
        volumes:
            - ./www:/var/www
        ports:
            - 8443:8443
            - 8800:8080

    phpmyadmin:
        build: ./phpmyadmin
        environment:
            PMA_ARBITRARY: 1
            MYSQL_USER: root
            MYSQL_PASSWORD: root
            MYSQL_ROOT_PASSWORD: root
        ports:
            - 8082:80
        links:
            - db
